name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_ACTIONS_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
      
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/store/flask-app:${{ github.sha }} ./lab1
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/store/flask-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/store/flask-app:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-secrets=DB_USER=DB_USER:latest,DB_HOST=DB_HOST:latest,DB_NAME=DB_NAME:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_PORT=DB_PORT:latest,IDENTITY_KEY=IDENTITY_KEY:latest \
            --set-env-vars=PROJECT_ID=bold-mantis-480720-d1 \
            --add-cloudsql-instances=bold-mantis-480720-d1:europe-west1:storedb \
            --min-instances 0 \
            --max-instances 3 \
            --cpu 1 \
            --memory 256Mi \
            --cpu-throttling \
            --concurrency 10 
